### ISSUE TITLE
Add mattermost-plugin-pingboard to the marketplace

### ISSUE THREAD

**Issue by grubbins** [mattermost/mattermost-marketplace#276]
#### Summary
Adds information from [Pingboard](https://pingboard.com/) to the user popover. See [README](https://github.com/imc-trading/mattermost-plugin-pingboard/blob/v1.0.0/README.md).

#### Review commit
https://github.com/imc-trading/mattermost-plugin-pingboard/releases/tag/v1.0.0

## Checklist

**Product requirements**

- [x] The plugin is published under an [Open Source license](https://opensource.org/licenses/alphabetical).
- [x] The source code is available in a public Git repository.
- [x] There is a public issue or bug tracker for the plugin, which is linked in the plugin documentation and linked via `support_url` in the manifest.
- [x] For the current release and upcoming ones a changelog has to be published, with a link recorded in the `release_notes_url` property of the `plugin.json` manifest.
- [x] The plugin has to be out of Beta and be released with at least v1.0.0.
- [x] All configuration is accessible via the Mattermost interface.
- [x] The plugin ID defined in the manifest must not collide with the ID of an existing plugin in the Marketplace. It should follow [the documentation's suggested naming convention](https://developers.mattermost.com/extend/plugins/manifest-reference/#id).

**Technical requirements**

- [x] The plugin works for 60k concurrent connections and in a High Availability deployment. **Note:** There are currently no publicly-available tools to verify these properties. As such, they are checked during code review by a developer.
- [x] The plugin logs important events on appropriate log levels to allow System Admins to troubleshoot issues.

**Security requirements**

- [ ] Security reviews do not reveal any exploitable vulnerabilities in the plugin.
- [ ] The plugin provides an email address or a username on the [Community Server](https://community.mattermost.com) used to report vulnerabilities in the future. Please post it into this issue or send it to ben.schumacher@mattermost.com.

**Functional requirements**

- [x] The plugin must set a `min_server_version` in the manifest.
- [ ] The plugin must work on all Mattermost versions greater than or equal to the `min_server_version`.

**Documentation requirements (checked by a Technical Writer)**

- [x] The plugin must include detailed usage documentation with at least one screenshot of the plugin in action, list of features, and a development guide. This is typically a `README` file or a landing page on the web. The link to the documentation is set as `homepage_url` in the manifest. A great example is the [`README` of the GitHub plugin](https://github.com/mattermost/mattermost-plugin-github/blob/master/README.md). Typical components of documentation include:

    * Requirements/Prerequisites
    * Installation steps
    * Configuration steps
    * Usage
    * Troubleshooting
    * Screenshots (if available)
    * Link or email address for help/support

The `plugin.json` file should include formatting consistent with the System Console interface. You can join the [Documentation channel](https://community.mattermost.com/core/channels/documentation) for assistance.

**Comment by hanzei** [comment]
@grubbins Thank you for submitting your plugin! Sorry, it took so long for me to get to it. I kicked of the review process and will provide an update to your shortly.

**Comment by wiersgallak** [comment]
Published to the web marketplace at: https://mattermost.com/marketplace/pingboard/

**Comment by esethna** [comment]
Hey @grubbins, my apologies on the large delay handling these issues. We've been working on some changes to the in-product marketplace in response to customer feedback.

We've heard that many Admins find it confusing that the [web marketplace](https://mattermost.com/marketplace/) and in-product marketplace have different offerings. Moving forward we will be [removing community plugins from the in-product marketplace](https://mattermost.atlassian.net/browse/MM-53030) and adding a [link in-product](https://mattermost.atlassian.net/browse/MM-52981) to direct Admins to the web marketplace to find all community supported plugins.

I can go ahead and close your open issue on this repo since we won't be updating the in-product marketplace moving forward. You can check out the latest process re web marketplace submissions here for more context: https://developers.mattermost.com/integrate/marketplace-submissions/

Thanks again for all your contributions, please let me know if you'd like to discuss this in more detail. You can ping me at @eric.sethna on the contributors server.
