### ISSUE TITLE
Update Matterpoll to 1.6.0

### ISSUE THREAD

**Issue by kaakaa** [mattermost/mattermost-marketplace#367]
#### Summary
* feat: Add RHS informations card to show users votes
* fix: With progress settings,  button color of votes answer is changed back as default unexpectedly
* fix: Latex with Matterpoll crashes web interface

See details in [Release 1\.6\.0](https://github.com/matterpoll/matterpoll/issues/476)

#### Review reference

Commit ~~https://github.com/matterpoll/matterpoll/commit/5bbd0f7a2cb8fa095923d7edbf160cdde4c20a4c~~ https://github.com/matterpoll/matterpoll/commit/aeaeebbe01c3d70f7b7cbf7968264ba8e9e5deb8 (v1.6.1 is released after creating this issue)

## Checklist

- [x] [All requirements](https://developers.mattermost.com/extend/plugins/community-plugin-marketplace/#requirements-for-adding-community-plugin-to-the-marketplace) are still met.
- [x] The release also has to follow [Semantic Versioning](https://semver.org/). For plugins in particular this means:
  - If the plugin exposes a public API, breaking changes to the API require a major version bump.
  - If an update requires manual migration actions from the System Admin, a major version bump is required.
- [x] A changelog has been published. The link to it is noted via `release_notes_url` in the manifest.

**Comment by esethna** [comment]
Hey @kaakaa, our apologies on the large delay handling these issues. We've been working on some changes to the in-product marketplace in response to customer feedback.

We've heard that many Admins find it confusing that the [web marketplace](https://mattermost.com/marketplace/) and in-product marketplace have different offerings. Moving forward we will be [removing community plugins from the in-product marketplace](https://mattermost.atlassian.net/browse/MM-53030) and adding a [link in-product](https://mattermost.atlassian.net/browse/MM-52981) to direct Admins to the web marketplace to find all community supported plugins.

Since this plugin is already added to the web marketplace, I can go ahead and close your open issue on this repo since we won't be updating the in-product marketplace moving forward. You can check out the latest process re web marketplace submissions if you'd like to make changes to the web marketplace listing: https://developers.mattermost.com/integrate/marketplace-submissions/

Thanks again for all your contributions, please let me know if you'd like to discuss this in more detail. You can ping me at @eric.sethna on the contributors server.
