### ISSUE TITLE
[Question] Plugins missing from marketplace

### ISSUE THREAD

**Issue by scmanjarrez** [mattermost/mattermost-marketplace#391]
Hi,
Do I need to configure something else after setting up my mattermost server? When I go to the built-in marketplace, only a subset of plugins are shown; if I search for matterpoll, it can't find it, however it appears in https://mattermost.com/marketplace/

![image](https://github.com/mattermost/mattermost-marketplace/assets/9284124/b05faafd-e437-4be3-b939-7258fbc0a1ff)
![image](https://github.com/mattermost/mattermost-marketplace/assets/9284124/1378c373-8055-4205-97ab-993c93d5f5c0)
![image](https://github.com/mattermost/mattermost-marketplace/assets/9284124/8029f9be-667f-4224-8d7d-60e6de03219d)
![image](https://github.com/mattermost/mattermost-marketplace/assets/9284124/1867a714-84c1-4669-a9cc-9e846e1e66e1)
![image](https://github.com/mattermost/mattermost-marketplace/assets/9284124/752a9f4f-c653-4044-881c-0cebfe18681b)

**Comment by esethna** [comment]
Thanks for the question. In v9.0 and later we've tried to make this distinction more clear, since the ones found in the poduct are supported by Mattermost, whereas the ones found on the website also include community driven integrations.
 
![image](https://github.com/mattermost/mattermost-marketplace/assets/14333569/cc39ea54-f92f-42d5-866e-73e8c4ef17da)

**Comment by scmanjarrez** [comment]
Thank you very much for your prompt response. So now the only way to install these kind of plugins is manually?

**Comment by hanzei** [comment]
@scmanjarrez That is indeed the case.
